sudo: required
dist: trusty

language: python

cache:
  bundler: true
  pip: true

python:
  - "2.7"
  #- "3.4"

node_js:
  - "6"

virtualenv:
  system_site_packages: true


exclude: [vendor]

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz -o /downloads/sip.tar.gz 
  - curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz -o /downloads/pyqt4.tar.gz
  #- curl -L http://www.pyqtgraph.org/downloads/0.10.0/pyqtgraph-0.10.0.tar.gz -o /downloads/pyqtgraph.tar.gz
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
 
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y libqt4-dev
  - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt  
  - sudo apt-get install -y python-numpy python-scipy
  - sudo apt-get install ruby
  - gem install jekyll

  # Node JS, NPM , Surge etc
  - nvm install 6
  # add node_modules/.bin to the path so that ember command is detected
  - export PATH=./node_modules/.bin:$PATH
  - npm install -g npm@5.3.0
  - npm config set spin false
  - node -v
  - npm -v
  - npm cache verify
  - npm install -g surge



install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    #Scipy
    #- sudo apt-get install -y python3-sip python3-sip-dev python3-pyqt4 cmake
    # Qt4
    - pushd /builds
    # SIP
    - tar xzf /downloads/sip.tar.gz --keep-newer-files
    - pushd sip-4.16.5
    - python configure.py
    - make
    - sudo make install
    - popd
    # PyQt4
    - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
    - pushd PyQt-x11-gpl-4.11.3
    - python configure.py -c --confirm-license -e QtCore -e QtGui -e QtTest -e QtDesigner -e QtWebKit -e QtNetwork -e QtSvg
    - make
    - sudo make install
    - popd

    # Builds Complete
    - popd
    - pip install -r requirements.txt

    # Our own code
    - make


script:
  - nosetests
  - pushd SPARK17/help
  - jekyll build
  # Details of a dummy account. So can be added to vcs.
  - export SURGE_LOGIN=jithinuser@gmail.com
  - export SURGE_TOKEN=41d3b52898d9b490a0c45d832e6a03ef
  - export DEPLOY_DOMAIN=https://eyes17-help.surge.sh
  - surge --project ./MD_HTML --domain $DEPLOY_DOMAIN;
  - popd




