language: python
cache: pip

python:
  - "2.7"


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
  - sudo apt-get install python-pyqt5 python-pyqt5.qtsvg python-pyqt5.qtwebkit

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - make

script:
  - python -m SPARK17.spark17


