name: ExpEYES-17 documentation

exclude: ['myapk','MD_HTML']
include: ['apps','utilities']
collections:
 apps:
  permalink: /apps/:path.html
  output: true
 utilities:
  permalink: /utilities/:path.html
  output: true

future: true
destination: MD_HTML
permalink: pretty
excerpt_separator: "<!--more-->"

markdown: kramdown
highlighter: rouge

kramdown:
 syntax_highlighter: rouge
 input: GFM

