# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 641)
        MainWindow.setStyleSheet("*{outline:none;}\n"
"\n"
"QMainWindow{background: rgb(56, 102, 115);} \n"
"QMessageBox {background: #444544;} \n"
"\n"
"QTabBar{font:16px;} \n"
"QTabBar::tab{ padding:10px 50px; color:#CCCCCC;background: rgb(56, 102, 115);}\n"
"QTabBar::tab:selected{color:white; background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:.7 rgb(126, 197, 220) , stop:1 rgba(0,0,0,100) );} \n"
"QTabBar::tab:hover{color:white; background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(26, 177, 191,255), stop:1 rgba(100, 100, 200,255) );} \n"
"\n"
".deep,#widgets{ background: rgb(57, 79, 99); }\n"
"\n"
"QListWidget{background: rgb(26, 32, 35);color:#FFFFFF;} \n"
"QListWidget::item:hover{background: #223344;color:#FFFFFF;} \n"
"\n"
"QLabel,QRadioButton{color:#FFFFFF; margin:1px 2px;}\n"
"QCheckBox{color:#FFFFEE; margin:3px 0px;}\n"
"\n"
"QSlider::groove:horizontal {margin:0px; padding:0px; border:none; background:#DDFDFE; color:#BB7777; height: 4px;}\n"
"QSlider::handle:horizontal {background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eee, stop:1 #ccc);border: 2px solid #777;width: 13px;margin-top: -3px;margin-bottom: -3px;border-radius: 3px;}\n"
"\n"
"QPushButton{border:1px solid #424242; padding:6px;color:#000000;background:#AAAAAA;}\n"
"QPushButton:hover{background:rgb(26, 177, 191) ; color:white; border-color:#FFFFFF;}\n"
"QPushButton::disabled{background:#333333 ; color:black;}\n"
"QComboBox QAbstractItemView::item {\n"
"    border-bottom: 5px solid white; margin:3px;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    border-bottom: 5px solid black; margin:3px;\n"
"}\n"
"\n"
"QToolTip{background:#FBE9E7;color:#757575; padding:4px; border:0px; margin:0px;} QPushButton{min-height24px; min-width:30px;}  ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.plots = QtWidgets.QFrame(self.splitter)
        self.plots.setMinimumSize(QtCore.QSize(600, 0))
        self.plots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plots.setObjectName("plots")
        self.plot_area = QtWidgets.QVBoxLayout(self.plots)
        self.plot_area.setSpacing(0)
        self.plot_area.setContentsMargins(0, 0, 0, 0)
        self.plot_area.setObjectName("plot_area")
        self.widgets = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgets.sizePolicy().hasHeightForWidth())
        self.widgets.setSizePolicy(sizePolicy)
        self.widgets.setMinimumSize(QtCore.QSize(250, 0))
        self.widgets.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widgets.setAutoFillBackground(False)
        self.widgets.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.widgets.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgets.setObjectName("widgets")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgets)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.widgets)
        self.comboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.comboBox.setIconSize(QtCore.QSize(0, 0))
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widgets)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.WGSLIDER = QtWidgets.QSlider(self.widgets)
        self.WGSLIDER.setMaximumSize(QtCore.QSize(16777215, 15))
        self.WGSLIDER.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.WGSLIDER.setMinimum(5)
        self.WGSLIDER.setMaximum(5000)
        self.WGSLIDER.setProperty("value", 1500)
        self.WGSLIDER.setOrientation(QtCore.Qt.Horizontal)
        self.WGSLIDER.setObjectName("WGSLIDER")
        self.gridLayout.addWidget(self.WGSLIDER, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widgets)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widgets)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_4.addWidget(self.checkBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 4)
        self.WGBOX = QtWidgets.QDoubleSpinBox(self.widgets)
        self.WGBOX.setMinimumSize(QtCore.QSize(55, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.WGBOX.setFont(font)
        self.WGBOX.setFrame(True)
        self.WGBOX.setAlignment(QtCore.Qt.AlignCenter)
        self.WGBOX.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.WGBOX.setDecimals(1)
        self.WGBOX.setMinimum(10.0)
        self.WGBOX.setMaximum(4000.0)
        self.WGBOX.setProperty("value", 1500.0)
        self.WGBOX.setObjectName("WGBOX")
        self.gridLayout.addWidget(self.WGBOX, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widgets)
        self.label.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.line_5 = QtWidgets.QFrame(self.widgets)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 6, 0, 1, 4)
        self.line_4 = QtWidgets.QFrame(self.widgets)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 4)
        self.line_6 = QtWidgets.QFrame(self.widgets)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 3, 0, 1, 4)
        self.controlLayout = QtWidgets.QVBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.gridLayout.addLayout(self.controlLayout, 7, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_3 = QtWidgets.QFrame(self.widgets)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_8 = QtWidgets.QLabel(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.widgets)
        self.comboBox_4.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.FITA1 = QtWidgets.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITA1.setFont(font)
        self.FITA1.setText("")
        self.FITA1.setObjectName("FITA1")
        self.gridLayout_3.addWidget(self.FITA1, 1, 2, 1, 1)
        self.FITA2 = QtWidgets.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITA2.setFont(font)
        self.FITA2.setText("")
        self.FITA2.setObjectName("FITA2")
        self.gridLayout_3.addWidget(self.FITA2, 2, 2, 1, 1)
        self.A3 = QtWidgets.QCheckBox(self.widgets)
        self.A3.setMaximumSize(QtCore.QSize(55, 16777215))
        self.A3.setObjectName("A3")
        self.gridLayout_3.addWidget(self.A3, 3, 0, 1, 1)
        self.A1RANGEBOX = QtWidgets.QComboBox(self.widgets)
        self.A1RANGEBOX.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.A1RANGEBOX.setFont(font)
        self.A1RANGEBOX.setObjectName("A1RANGEBOX")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.A1RANGEBOX.addItem("")
        self.gridLayout_3.addWidget(self.A1RANGEBOX, 1, 1, 1, 1)
        self.A2 = QtWidgets.QCheckBox(self.widgets)
        self.A2.setMaximumSize(QtCore.QSize(55, 16777215))
        self.A2.setChecked(True)
        self.A2.setObjectName("A2")
        self.gridLayout_3.addWidget(self.A2, 2, 0, 1, 1)
        self.A1RANGEBOX_2 = QtWidgets.QComboBox(self.widgets)
        self.A1RANGEBOX_2.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.A1RANGEBOX_2.setFont(font)
        self.A1RANGEBOX_2.setObjectName("A1RANGEBOX_2")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.A1RANGEBOX_2.addItem("")
        self.gridLayout_3.addWidget(self.A1RANGEBOX_2, 2, 1, 1, 1)
        self.MIC = QtWidgets.QCheckBox(self.widgets)
        self.MIC.setMaximumSize(QtCore.QSize(55, 16777215))
        self.MIC.setObjectName("MIC")
        self.gridLayout_3.addWidget(self.MIC, 4, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.widgets)
        self.comboBox_5.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_5, 4, 1, 1, 1)
        self.FITA3 = QtWidgets.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITA3.setFont(font)
        self.FITA3.setText("")
        self.FITA3.setObjectName("FITA3")
        self.gridLayout_3.addWidget(self.FITA3, 3, 2, 1, 1)
        self.FITMIC = QtWidgets.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITMIC.setFont(font)
        self.FITMIC.setText("")
        self.FITMIC.setObjectName("FITMIC")
        self.gridLayout_3.addWidget(self.FITMIC, 4, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.A1 = QtWidgets.QCheckBox(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1.sizePolicy().hasHeightForWidth())
        self.A1.setSizePolicy(sizePolicy)
        self.A1.setMaximumSize(QtCore.QSize(55, 16777215))
        self.A1.setText("")
        self.A1.setChecked(True)
        self.A1.setObjectName("A1")
        self.horizontalLayout_6.addWidget(self.A1)
        self.chan1Box = QtWidgets.QComboBox(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chan1Box.sizePolicy().hasHeightForWidth())
        self.chan1Box.setSizePolicy(sizePolicy)
        self.chan1Box.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chan1Box.setFont(font)
        self.chan1Box.setObjectName("chan1Box")
        self.horizontalLayout_6.addWidget(self.chan1Box)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widgets)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widgets)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widgets)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tgLabel_2 = QtWidgets.QLabel(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgLabel_2.sizePolicy().hasHeightForWidth())
        self.tgLabel_2.setSizePolicy(sizePolicy)
        self.tgLabel_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tgLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tgLabel_2.setObjectName("tgLabel_2")
        self.horizontalLayout_9.addWidget(self.tgLabel_2)
        self.SQ1SLIDER_5 = QtWidgets.QSlider(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQ1SLIDER_5.sizePolicy().hasHeightForWidth())
        self.SQ1SLIDER_5.setSizePolicy(sizePolicy)
        self.SQ1SLIDER_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.SQ1SLIDER_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SQ1SLIDER_5.setMinimum(0)
        self.SQ1SLIDER_5.setMaximum(9)
        self.SQ1SLIDER_5.setSingleStep(1)
        self.SQ1SLIDER_5.setPageStep(1)
        self.SQ1SLIDER_5.setProperty("value", 0)
        self.SQ1SLIDER_5.setOrientation(QtCore.Qt.Horizontal)
        self.SQ1SLIDER_5.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.SQ1SLIDER_5.setTickInterval(0)
        self.SQ1SLIDER_5.setObjectName("SQ1SLIDER_5")
        self.horizontalLayout_9.addWidget(self.SQ1SLIDER_5)
        self.tgLabel = QtWidgets.QLabel(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgLabel.sizePolicy().hasHeightForWidth())
        self.tgLabel.setSizePolicy(sizePolicy)
        self.tgLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.tgLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tgLabel.setObjectName("tgLabel")
        self.horizontalLayout_9.addWidget(self.tgLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.trigBox = QtWidgets.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trigBox.setFont(font)
        self.trigBox.setObjectName("trigBox")
        self.horizontalLayout_3.addWidget(self.trigBox)
        self.pushButton = QtWidgets.QPushButton(self.widgets)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_7 = QtWidgets.QFrame(self.widgets)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_6 = QtWidgets.QPushButton(self.widgets)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.line = QtWidgets.QFrame(self.widgets)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.experimentBox = QtWidgets.QComboBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.experimentBox.setFont(font)
        self.experimentBox.setMaxCount(200)
        self.experimentBox.setFrame(False)
        self.experimentBox.setObjectName("experimentBox")
        self.horizontalLayout.addWidget(self.experimentBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.widgets)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.widgets)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.pauseBox = QtWidgets.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pauseBox.setFont(font)
        self.pauseBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pauseBox.setObjectName("pauseBox")
        self.verticalLayout.addWidget(self.pauseBox)
        self.horizontalLayout_2.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/control/plots.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.controlTab = QtWidgets.QWidget()
        self.controlTab.setObjectName("controlTab")
        self.frame_12 = QtWidgets.QFrame(self.controlTab)
        self.frame_12.setGeometry(QtCore.QRect(10, 60, 300, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_12)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(3)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timeoutBox = QtWidgets.QSpinBox(self.frame_7)
        self.timeoutBox.setMinimum(10)
        self.timeoutBox.setMaximum(10000)
        self.timeoutBox.setObjectName("timeoutBox")
        self.gridLayout_4.addWidget(self.timeoutBox, 4, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_4.addWidget(self.pushButton_7, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 4, 0, 1, 2)
        self.edge2edge = QtWidgets.QComboBox(self.frame_7)
        self.edge2edge.setObjectName("edge2edge")
        self.edge2edge.addItem("")
        self.edge2edge.addItem("")
        self.edge2edge.addItem("")
        self.gridLayout_4.addWidget(self.edge2edge, 3, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 4)
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.edge1edge = QtWidgets.QComboBox(self.frame_7)
        self.edge1edge.setObjectName("edge1edge")
        self.edge1edge.addItem("")
        self.edge1edge.addItem("")
        self.edge1edge.addItem("")
        self.gridLayout_4.addWidget(self.edge1edge, 2, 2, 1, 1)
        self.edge2chan = QtWidgets.QComboBox(self.frame_7)
        self.edge2chan.setObjectName("edge2chan")
        self.gridLayout_4.addWidget(self.edge2chan, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.edge1chan = QtWidgets.QComboBox(self.frame_7)
        self.edge1chan.setObjectName("edge1chan")
        self.gridLayout_4.addWidget(self.edge1chan, 2, 1, 1, 1)
        self.edge1Count = QtWidgets.QComboBox(self.frame_7)
        self.edge1Count.setObjectName("edge1Count")
        self.edge1Count.addItem("")
        self.edge1Count.addItem("")
        self.edge1Count.addItem("")
        self.edge1Count.addItem("")
        self.gridLayout_4.addWidget(self.edge1Count, 2, 3, 1, 1)
        self.edge2Count = QtWidgets.QComboBox(self.frame_7)
        self.edge2Count.setObjectName("edge2Count")
        self.edge2Count.addItem("")
        self.edge2Count.addItem("")
        self.edge2Count.addItem("")
        self.edge2Count.addItem("")
        self.gridLayout_4.addWidget(self.edge2Count, 3, 3, 1, 1)
        self.timingResults = QtWidgets.QTableWidget(self.frame_7)
        self.timingResults.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timingResults.setShowGrid(True)
        self.timingResults.setCornerButtonEnabled(True)
        self.timingResults.setRowCount(4)
        self.timingResults.setColumnCount(2)
        self.timingResults.setObjectName("timingResults")
        self.timingResults.horizontalHeader().setVisible(False)
        self.timingResults.horizontalHeader().setDefaultSectionSize(115)
        self.timingResults.horizontalHeader().setMinimumSectionSize(60)
        self.timingResults.horizontalHeader().setStretchLastSection(True)
        self.timingResults.verticalHeader().setDefaultSectionSize(22)
        self.timingResults.verticalHeader().setMinimumSectionSize(20)
        self.timingResults.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.timingResults, 10, 0, 1, 4)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.controlTab)
        self.frame_13.setGeometry(QtCore.QRect(320, 60, 300, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_13)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(3)
        self.gridLayout_6.setVerticalSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.TimeoutBox = QtWidgets.QSpinBox(self.frame_8)
        self.TimeoutBox.setMinimum(10)
        self.TimeoutBox.setMaximum(10000)
        self.TimeoutBox.setObjectName("TimeoutBox")
        self.gridLayout_6.addWidget(self.TimeoutBox, 4, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_6.addWidget(self.pushButton_8, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 4, 0, 1, 2)
        self.Edge2edge = QtWidgets.QComboBox(self.frame_8)
        self.Edge2edge.setObjectName("Edge2edge")
        self.Edge2edge.addItem("")
        self.Edge2edge.addItem("")
        self.Edge2edge.addItem("")
        self.Edge2edge.addItem("")
        self.gridLayout_6.addWidget(self.Edge2edge, 3, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 0, 0, 1, 4)
        self.label_18 = QtWidgets.QLabel(self.frame_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)
        self.Edge1edge = QtWidgets.QComboBox(self.frame_8)
        self.Edge1edge.setObjectName("Edge1edge")
        self.Edge1edge.addItem("")
        self.Edge1edge.addItem("")
        self.Edge1edge.addItem("")
        self.Edge1edge.addItem("")
        self.gridLayout_6.addWidget(self.Edge1edge, 2, 2, 1, 1)
        self.Edge2chan = QtWidgets.QComboBox(self.frame_8)
        self.Edge2chan.setObjectName("Edge2chan")
        self.gridLayout_6.addWidget(self.Edge2chan, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 3, 0, 1, 1)
        self.Edge1chan = QtWidgets.QComboBox(self.frame_8)
        self.Edge1chan.setObjectName("Edge1chan")
        self.gridLayout_6.addWidget(self.Edge1chan, 2, 1, 1, 1)
        self.Edge1Count = QtWidgets.QComboBox(self.frame_8)
        self.Edge1Count.setObjectName("Edge1Count")
        self.Edge1Count.addItem("")
        self.Edge1Count.addItem("")
        self.Edge1Count.addItem("")
        self.Edge1Count.addItem("")
        self.gridLayout_6.addWidget(self.Edge1Count, 2, 3, 1, 1)
        self.Edge2Count = QtWidgets.QComboBox(self.frame_8)
        self.Edge2Count.setObjectName("Edge2Count")
        self.Edge2Count.addItem("")
        self.Edge2Count.addItem("")
        self.Edge2Count.addItem("")
        self.Edge2Count.addItem("")
        self.gridLayout_6.addWidget(self.Edge2Count, 3, 3, 1, 1)
        self.TimingResults = QtWidgets.QTableWidget(self.frame_8)
        self.TimingResults.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TimingResults.setShowGrid(True)
        self.TimingResults.setCornerButtonEnabled(True)
        self.TimingResults.setRowCount(4)
        self.TimingResults.setColumnCount(2)
        self.TimingResults.setObjectName("TimingResults")
        self.TimingResults.horizontalHeader().setVisible(False)
        self.TimingResults.horizontalHeader().setDefaultSectionSize(115)
        self.TimingResults.horizontalHeader().setMinimumSectionSize(60)
        self.TimingResults.horizontalHeader().setStretchLastSection(True)
        self.TimingResults.verticalHeader().setDefaultSectionSize(22)
        self.TimingResults.verticalHeader().setMinimumSectionSize(20)
        self.TimingResults.verticalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.TimingResults, 10, 0, 1, 4)
        self.gridLayout_5.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.controlTab)
        self.frame_14.setGeometry(QtCore.QRect(10, 295, 300, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.frame_14)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(3)
        self.gridLayout_8.setVerticalSpacing(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.timeoutBox_3 = QtWidgets.QSpinBox(self.frame_9)
        self.timeoutBox_3.setMinimum(10)
        self.timeoutBox_3.setMaximum(10000)
        self.timeoutBox_3.setObjectName("timeoutBox_3")
        self.gridLayout_8.addWidget(self.timeoutBox_3, 3, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_8.addWidget(self.pushButton_9, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 3, 0, 1, 2)
        self.label_58 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_8.addWidget(self.label_58, 0, 0, 1, 4)
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 2, 0, 1, 1)
        self.edge1edge_3 = QtWidgets.QComboBox(self.frame_9)
        self.edge1edge_3.setObjectName("edge1edge_3")
        self.edge1edge_3.addItem("")
        self.edge1edge_3.addItem("")
        self.edge1edge_3.addItem("")
        self.gridLayout_8.addWidget(self.edge1edge_3, 2, 2, 1, 1)
        self.edge1chan_3 = QtWidgets.QComboBox(self.frame_9)
        self.edge1chan_3.setObjectName("edge1chan_3")
        self.gridLayout_8.addWidget(self.edge1chan_3, 2, 1, 1, 1)
        self.edge1Count_3 = QtWidgets.QComboBox(self.frame_9)
        self.edge1Count_3.setObjectName("edge1Count_3")
        self.edge1Count_3.addItem("")
        self.edge1Count_3.addItem("")
        self.edge1Count_3.addItem("")
        self.edge1Count_3.addItem("")
        self.gridLayout_8.addWidget(self.edge1Count_3, 2, 3, 1, 1)
        self.timingResults_3 = QtWidgets.QTableWidget(self.frame_9)
        self.timingResults_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timingResults_3.setShowGrid(True)
        self.timingResults_3.setCornerButtonEnabled(True)
        self.timingResults_3.setRowCount(4)
        self.timingResults_3.setColumnCount(1)
        self.timingResults_3.setObjectName("timingResults_3")
        self.timingResults_3.horizontalHeader().setVisible(False)
        self.timingResults_3.horizontalHeader().setDefaultSectionSize(115)
        self.timingResults_3.horizontalHeader().setMinimumSectionSize(60)
        self.timingResults_3.horizontalHeader().setStretchLastSection(True)
        self.timingResults_3.verticalHeader().setDefaultSectionSize(22)
        self.timingResults_3.verticalHeader().setMinimumSectionSize(20)
        self.timingResults_3.verticalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.timingResults_3, 9, 0, 1, 4)
        self.gridLayout_7.addWidget(self.frame_9, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.controlTab)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.DIN_IN2 = QtWidgets.QLabel(self.groupBox)
        self.DIN_IN2.setStyleSheet("")
        self.DIN_IN2.setObjectName("DIN_IN2")
        self.horizontalLayout_11.addWidget(self.DIN_IN2)
        self.DIN_SQR1 = QtWidgets.QLabel(self.groupBox)
        self.DIN_SQR1.setObjectName("DIN_SQR1")
        self.horizontalLayout_11.addWidget(self.DIN_SQR1)
        self.DIN_OD1 = QtWidgets.QLabel(self.groupBox)
        self.DIN_OD1.setObjectName("DIN_OD1")
        self.horizontalLayout_11.addWidget(self.DIN_OD1)
        self.DIN_SEN = QtWidgets.QLabel(self.groupBox)
        self.DIN_SEN.setObjectName("DIN_SEN")
        self.horizontalLayout_11.addWidget(self.DIN_SEN)
        self.DIN_CCS = QtWidgets.QLabel(self.groupBox)
        self.DIN_CCS.setObjectName("DIN_CCS")
        self.horizontalLayout_11.addWidget(self.DIN_CCS)
        self.tabWidget.addTab(self.controlTab, "")
        self.experimentTab = QtWidgets.QWidget()
        self.experimentTab.setObjectName("experimentTab")
        self.experimentLayout = QtWidgets.QVBoxLayout(self.experimentTab)
        self.experimentLayout.setContentsMargins(0, 0, 0, 0)
        self.experimentLayout.setObjectName("experimentLayout")
        self.tabWidget.addTab(self.experimentTab, "")
        self.saveTab = QtWidgets.QWidget()
        self.saveTab.setObjectName("saveTab")
        self.saveLayout = QtWidgets.QVBoxLayout(self.saveTab)
        self.saveLayout.setSpacing(0)
        self.saveLayout.setContentsMargins(0, 0, 0, 0)
        self.saveLayout.setObjectName("saveLayout")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/control/saved.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.saveTab, icon1, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.A1RANGEBOX.setCurrentIndex(2)
        self.A1RANGEBOX_2.setCurrentIndex(2)
        self.chan1Box.setCurrentIndex(-1)
        self.edge2edge.setCurrentIndex(1)
        self.edge1Count.setCurrentIndex(0)
        self.Edge2edge.setCurrentIndex(1)
        self.Edge1Count.setCurrentIndex(0)
        self.edge1Count_3.setCurrentIndex(0)
        self.pushButton_6.clicked.connect(MainWindow.save)
        self.A1RANGEBOX.currentIndexChanged['int'].connect(MainWindow.setGainA1)
        self.A1RANGEBOX_2.currentIndexChanged['int'].connect(MainWindow.setGainA2)
        self.comboBox_4.currentIndexChanged['int'].connect(MainWindow.setGainA3)
        self.comboBox_5.currentIndexChanged['int'].connect(MainWindow.setGainMIC)
        self.comboBox.currentIndexChanged['int'].connect(MainWindow.setSineAmp)
        self.chan1Box.currentIndexChanged['QString'].connect(MainWindow.setCH1Remap)
        self.SQ1SLIDER_5.valueChanged['int'].connect(MainWindow.setTimebase)
        self.pushButton_7.clicked.connect(MainWindow.measure_interval)
        self.pushButton_8.clicked.connect(MainWindow.DoubleInputInterval)
        self.tabWidget.currentChanged['int'].connect(MainWindow.tabChanged)
        self.pushButton_2.clicked.connect(MainWindow.launchExperiment)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExpEYES - 17"))
        self.widgets.setProperty("class", _translate("MainWindow", "deep"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SINE .1V"))
        self.comboBox.setItemText(1, _translate("MainWindow", "SINE 1V"))
        self.comboBox.setItemText(2, _translate("MainWindow", "SINE 3V"))
        self.comboBox.setItemText(3, _translate("MainWindow", "TRIA .1V"))
        self.comboBox.setItemText(4, _translate("MainWindow", "TRIA 1V"))
        self.comboBox.setItemText(5, _translate("MainWindow", "TRIA 3V"))
        self.comboBox.setItemText(6, _translate("MainWindow", "SQR2"))
        self.label_3.setText(_translate("MainWindow", "WG"))
        self.checkBox_2.setText(_translate("MainWindow", "OD1"))
        self.checkBox_3.setText(_translate("MainWindow", "CCS"))
        self.label.setText(_translate("MainWindow", "Set Outputs"))
        self.label_8.setText(_translate("MainWindow", "Four Channel Oscilloscope"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "4V"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2V"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "1V"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", ".5V"))
        self.A3.setText(_translate("MainWindow", "A3"))
        self.A1RANGEBOX.setItemText(0, _translate("MainWindow", "16V"))
        self.A1RANGEBOX.setItemText(1, _translate("MainWindow", "8V"))
        self.A1RANGEBOX.setItemText(2, _translate("MainWindow", "4V"))
        self.A1RANGEBOX.setItemText(3, _translate("MainWindow", "2.5V"))
        self.A1RANGEBOX.setItemText(4, _translate("MainWindow", "1.5V"))
        self.A1RANGEBOX.setItemText(5, _translate("MainWindow", "1V"))
        self.A1RANGEBOX.setItemText(6, _translate("MainWindow", ".5V"))
        self.A1RANGEBOX.setItemText(7, _translate("MainWindow", ".25V"))
        self.A2.setText(_translate("MainWindow", "A2"))
        self.A1RANGEBOX_2.setItemText(0, _translate("MainWindow", "16V"))
        self.A1RANGEBOX_2.setItemText(1, _translate("MainWindow", "8V"))
        self.A1RANGEBOX_2.setItemText(2, _translate("MainWindow", "4V"))
        self.A1RANGEBOX_2.setItemText(3, _translate("MainWindow", "2.5V"))
        self.A1RANGEBOX_2.setItemText(4, _translate("MainWindow", "1.5V"))
        self.A1RANGEBOX_2.setItemText(5, _translate("MainWindow", "1V"))
        self.A1RANGEBOX_2.setItemText(6, _translate("MainWindow", ".5V"))
        self.A1RANGEBOX_2.setItemText(7, _translate("MainWindow", ".25V"))
        self.MIC.setText(_translate("MainWindow", "MIC"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "4V"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2V"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "1V"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", ".5V"))
        self.label_4.setText(_translate("MainWindow", "FIT"))
        self.label_6.setText(_translate("MainWindow", "Range"))
        self.label_7.setText(_translate("MainWindow", "Input"))
        self.tgLabel_2.setText(_translate("MainWindow", "Time"))
        self.tgLabel.setText(_translate("MainWindow", "mS"))
        self.trigBox.setText(_translate("MainWindow", "Trigger: 0V (Drag yellow line)"))
        self.pushButton.setText(_translate("MainWindow", "?"))
        self.pushButton.setShortcut(_translate("MainWindow", "T"))
        self.pushButton_6.setText(_translate("MainWindow", "Save Data"))
        self.pushButton_6.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.pushButton_2.setText(_translate("MainWindow", "LAUNCH"))
        self.pauseBox.setText(_translate("MainWindow", "PAUSE"))
        self.pauseBox.setShortcut(_translate("MainWindow", "Space"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Oscilloscope"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data Acquisition and controls"))
        self.frame_12.setProperty("class", _translate("MainWindow", "deep"))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.timeoutBox.setSuffix(_translate("MainWindow", "mS"))
        self.pushButton_7.setText(_translate("MainWindow", "Measure >"))
        self.label_2.setText(_translate("MainWindow", "Timeout:"))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising"))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling"))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.label_56.setText(_translate("MainWindow", "TIME INTERVAL MEASUREMENT"))
        self.label_16.setText(_translate("MainWindow", "1"))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising"))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling"))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.label_17.setText(_translate("MainWindow", "2"))
        self.edge1Count.setItemText(0, _translate("MainWindow", "1"))
        self.edge1Count.setItemText(1, _translate("MainWindow", "2"))
        self.edge1Count.setItemText(2, _translate("MainWindow", "3"))
        self.edge1Count.setItemText(3, _translate("MainWindow", "4"))
        self.edge2Count.setItemText(0, _translate("MainWindow", "1"))
        self.edge2Count.setItemText(1, _translate("MainWindow", "2"))
        self.edge2Count.setItemText(2, _translate("MainWindow", "3"))
        self.edge2Count.setItemText(3, _translate("MainWindow", "4"))
        self.frame_13.setProperty("class", _translate("MainWindow", "deep"))
        self.frame_8.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.TimeoutBox.setSuffix(_translate("MainWindow", "mS"))
        self.pushButton_8.setText(_translate("MainWindow", "Measure >"))
        self.label_5.setText(_translate("MainWindow", "Timeout:"))
        self.Edge2edge.setItemText(0, _translate("MainWindow", "rising"))
        self.Edge2edge.setItemText(1, _translate("MainWindow", "falling"))
        self.Edge2edge.setItemText(2, _translate("MainWindow", "4xrising"))
        self.Edge2edge.setItemText(3, _translate("MainWindow", "16xrising"))
        self.label_57.setText(_translate("MainWindow", "DOUBLE INPUT INTERVAL"))
        self.label_18.setText(_translate("MainWindow", "1"))
        self.Edge1edge.setItemText(0, _translate("MainWindow", "rising"))
        self.Edge1edge.setItemText(1, _translate("MainWindow", "falling"))
        self.Edge1edge.setItemText(2, _translate("MainWindow", "4xrising"))
        self.Edge1edge.setItemText(3, _translate("MainWindow", "16xrising"))
        self.label_19.setText(_translate("MainWindow", "2"))
        self.Edge1Count.setItemText(0, _translate("MainWindow", "1"))
        self.Edge1Count.setItemText(1, _translate("MainWindow", "2"))
        self.Edge1Count.setItemText(2, _translate("MainWindow", "3"))
        self.Edge1Count.setItemText(3, _translate("MainWindow", "4"))
        self.Edge2Count.setItemText(0, _translate("MainWindow", "1"))
        self.Edge2Count.setItemText(1, _translate("MainWindow", "2"))
        self.Edge2Count.setItemText(2, _translate("MainWindow", "3"))
        self.Edge2Count.setItemText(3, _translate("MainWindow", "4"))
        self.frame_14.setProperty("class", _translate("MainWindow", "deep"))
        self.frame_9.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner"))
        self.timeoutBox_3.setSuffix(_translate("MainWindow", "mS"))
        self.pushButton_9.setText(_translate("MainWindow", "Measure >"))
        self.label_9.setText(_translate("MainWindow", "Timeout:"))
        self.label_58.setText(_translate("MainWindow", "SINGLE INPUT INTERVAL"))
        self.label_20.setText(_translate("MainWindow", "1"))
        self.edge1edge_3.setItemText(0, _translate("MainWindow", "rising"))
        self.edge1edge_3.setItemText(1, _translate("MainWindow", "falling"))
        self.edge1edge_3.setItemText(2, _translate("MainWindow", "four rising edges"))
        self.edge1Count_3.setItemText(0, _translate("MainWindow", "1"))
        self.edge1Count_3.setItemText(1, _translate("MainWindow", "2"))
        self.edge1Count_3.setItemText(2, _translate("MainWindow", "3"))
        self.edge1Count_3.setItemText(3, _translate("MainWindow", "4"))
        self.groupBox.setTitle(_translate("MainWindow", "Digital Inputs"))
        self.DIN_IN2.setText(_translate("MainWindow", "IN2"))
        self.DIN_SQR1.setText(_translate("MainWindow", "SQR1"))
        self.DIN_OD1.setText(_translate("MainWindow", "OD1"))
        self.DIN_SEN.setText(_translate("MainWindow", "SEN"))
        self.DIN_CCS.setText(_translate("MainWindow", "CCS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlTab), _translate("MainWindow", "Measurement and Controls"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.experimentTab), _translate("MainWindow", "Experiments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saveTab), _translate("MainWindow", "Saved plots"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.saveTab), _translate("MainWindow", "View saved plots. Click on them to load them to the plot window for analysis"))

import res_rc
