# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(982, 641)
        MainWindow.setStyleSheet(_fromUtf8("*{outline:none;}\n"
"\n"
"QMainWindow{background: rgb(56, 102, 115);} \n"
"QMessageBox {background: #444544;} \n"
"\n"
"QTabBar{font:16px;} \n"
"QTabBar::tab{ padding:10px 50px; color:#CCCCCC;background: rgb(56, 102, 115);}\n"
"QTabBar::tab:selected{color:white; background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:.7 rgb(126, 197, 220) , stop:1 rgba(0,0,0,100) );} \n"
"QTabBar::tab:hover{color:white; background:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(26, 177, 191,255), stop:1 rgba(100, 100, 200,255) );} \n"
"\n"
".deep,#widgets{ background: rgb(57, 79, 99); }\n"
"\n"
"QListWidget{background: rgb(26, 32, 35);color:#FFFFFF;} \n"
"QListWidget::item:hover{background: #223344;color:#FFFFFF;} \n"
"\n"
"QLabel,QRadioButton{color:#FFFFFF; margin:1px 2px;}\n"
"QCheckBox{color:#FFFFEE; margin:3px 0px;}\n"
"\n"
"QSlider::groove:horizontal {margin:0px; padding:0px; border:none; background:#DDFDFE; color:#BB7777; height: 4px;}\n"
"QSlider::handle:horizontal {background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eee, stop:1 #ccc);border: 2px solid #777;width: 13px;margin-top: -3px;margin-bottom: -3px;border-radius: 3px;}\n"
"\n"
"QPushButton{border:1px solid #424242; padding:6px;color:#000000;background:#AAAAAA;}\n"
"QPushButton:hover{background:rgb(26, 177, 191) ; color:white; border-color:#FFFFFF;}\n"
"QPushButton::disabled{background:#333333 ; color:black;}\n"
"QComboBox QAbstractItemView::item {\n"
"    border-bottom: 5px solid white; margin:3px;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    border-bottom: 5px solid black; margin:3px;\n"
"}\n"
"\n"
"QToolTip{background:#FBE9E7;color:#757575; padding:4px; border:0px; margin:0px;} QPushButton{min-height24px; min-width:30px;}  "))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plots = QtGui.QFrame(self.splitter)
        self.plots.setMinimumSize(QtCore.QSize(600, 0))
        self.plots.setFrameShape(QtGui.QFrame.NoFrame)
        self.plots.setFrameShadow(QtGui.QFrame.Raised)
        self.plots.setObjectName(_fromUtf8("plots"))
        self.plot_area = QtGui.QVBoxLayout(self.plots)
        self.plot_area.setMargin(0)
        self.plot_area.setSpacing(0)
        self.plot_area.setObjectName(_fromUtf8("plot_area"))
        self.widgets = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgets.sizePolicy().hasHeightForWidth())
        self.widgets.setSizePolicy(sizePolicy)
        self.widgets.setMinimumSize(QtCore.QSize(250, 0))
        self.widgets.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widgets.setAutoFillBackground(False)
        self.widgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.widgets.setFrameShadow(QtGui.QFrame.Raised)
        self.widgets.setObjectName(_fromUtf8("widgets"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widgets)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox = QtGui.QComboBox(self.widgets)
        self.comboBox.setMinimumSize(QtCore.QSize(75, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.comboBox.setIconSize(QtCore.QSize(0, 0))
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 4, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.widgets)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.WGSLIDER = QtGui.QSlider(self.widgets)
        self.WGSLIDER.setMaximumSize(QtCore.QSize(16777215, 15))
        self.WGSLIDER.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.WGSLIDER.setMinimum(5)
        self.WGSLIDER.setMaximum(5000)
        self.WGSLIDER.setProperty("value", 1500)
        self.WGSLIDER.setOrientation(QtCore.Qt.Horizontal)
        self.WGSLIDER.setObjectName(_fromUtf8("WGSLIDER"))
        self.gridLayout.addWidget(self.WGSLIDER, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_2 = QtGui.QCheckBox(self.widgets)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.widgets)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_4.addWidget(self.checkBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 4)
        self.WGBOX = QtGui.QDoubleSpinBox(self.widgets)
        self.WGBOX.setMinimumSize(QtCore.QSize(55, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.WGBOX.setFont(font)
        self.WGBOX.setFrame(True)
        self.WGBOX.setAlignment(QtCore.Qt.AlignCenter)
        self.WGBOX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.WGBOX.setDecimals(1)
        self.WGBOX.setMinimum(10.0)
        self.WGBOX.setMaximum(4000.0)
        self.WGBOX.setProperty("value", 1500.0)
        self.WGBOX.setObjectName(_fromUtf8("WGBOX"))
        self.gridLayout.addWidget(self.WGBOX, 4, 2, 1, 1)
        self.label = QtGui.QLabel(self.widgets)
        self.label.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.line_5 = QtGui.QFrame(self.widgets)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 6, 0, 1, 4)
        self.line_4 = QtGui.QFrame(self.widgets)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 4)
        self.line_6 = QtGui.QFrame(self.widgets)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 3, 0, 1, 4)
        self.controlLayout = QtGui.QVBoxLayout()
        self.controlLayout.setObjectName(_fromUtf8("controlLayout"))
        self.gridLayout.addLayout(self.controlLayout, 7, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_3 = QtGui.QFrame(self.widgets)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.label_8 = QtGui.QLabel(self.widgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBox_4 = QtGui.QComboBox(self.widgets)
        self.comboBox_4.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.FITA1 = QtGui.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITA1.setFont(font)
        self.FITA1.setText(_fromUtf8(""))
        self.FITA1.setObjectName(_fromUtf8("FITA1"))
        self.gridLayout_3.addWidget(self.FITA1, 1, 2, 1, 1)
        self.FITA2 = QtGui.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITA2.setFont(font)
        self.FITA2.setText(_fromUtf8(""))
        self.FITA2.setObjectName(_fromUtf8("FITA2"))
        self.gridLayout_3.addWidget(self.FITA2, 2, 2, 1, 1)
        self.A3 = QtGui.QCheckBox(self.widgets)
        self.A3.setMaximumSize(QtCore.QSize(55, 16777215))
        self.A3.setObjectName(_fromUtf8("A3"))
        self.gridLayout_3.addWidget(self.A3, 3, 0, 1, 1)
        self.A1RANGEBOX = QtGui.QComboBox(self.widgets)
        self.A1RANGEBOX.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.A1RANGEBOX.setFont(font)
        self.A1RANGEBOX.setObjectName(_fromUtf8("A1RANGEBOX"))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.A1RANGEBOX.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.A1RANGEBOX, 1, 1, 1, 1)
        self.A2 = QtGui.QCheckBox(self.widgets)
        self.A2.setMaximumSize(QtCore.QSize(55, 16777215))
        self.A2.setChecked(True)
        self.A2.setObjectName(_fromUtf8("A2"))
        self.gridLayout_3.addWidget(self.A2, 2, 0, 1, 1)
        self.A1RANGEBOX_2 = QtGui.QComboBox(self.widgets)
        self.A1RANGEBOX_2.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.A1RANGEBOX_2.setFont(font)
        self.A1RANGEBOX_2.setObjectName(_fromUtf8("A1RANGEBOX_2"))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.A1RANGEBOX_2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.A1RANGEBOX_2, 2, 1, 1, 1)
        self.MIC = QtGui.QCheckBox(self.widgets)
        self.MIC.setMaximumSize(QtCore.QSize(55, 16777215))
        self.MIC.setObjectName(_fromUtf8("MIC"))
        self.gridLayout_3.addWidget(self.MIC, 4, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.widgets)
        self.comboBox_5.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_5, 4, 1, 1, 1)
        self.FITA3 = QtGui.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITA3.setFont(font)
        self.FITA3.setText(_fromUtf8(""))
        self.FITA3.setObjectName(_fromUtf8("FITA3"))
        self.gridLayout_3.addWidget(self.FITA3, 3, 2, 1, 1)
        self.FITMIC = QtGui.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.FITMIC.setFont(font)
        self.FITMIC.setText(_fromUtf8(""))
        self.FITMIC.setObjectName(_fromUtf8("FITMIC"))
        self.gridLayout_3.addWidget(self.FITMIC, 4, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.A1 = QtGui.QCheckBox(self.widgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1.sizePolicy().hasHeightForWidth())
        self.A1.setSizePolicy(sizePolicy)
        self.A1.setMaximumSize(QtCore.QSize(55, 16777215))
        self.A1.setText(_fromUtf8(""))
        self.A1.setChecked(True)
        self.A1.setObjectName(_fromUtf8("A1"))
        self.horizontalLayout_6.addWidget(self.A1)
        self.chan1Box = QtGui.QComboBox(self.widgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chan1Box.sizePolicy().hasHeightForWidth())
        self.chan1Box.setSizePolicy(sizePolicy)
        self.chan1Box.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chan1Box.setFont(font)
        self.chan1Box.setObjectName(_fromUtf8("chan1Box"))
        self.horizontalLayout_6.addWidget(self.chan1Box)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widgets)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.widgets)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widgets)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tgLabel_2 = QtGui.QLabel(self.widgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgLabel_2.sizePolicy().hasHeightForWidth())
        self.tgLabel_2.setSizePolicy(sizePolicy)
        self.tgLabel_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tgLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tgLabel_2.setObjectName(_fromUtf8("tgLabel_2"))
        self.horizontalLayout_9.addWidget(self.tgLabel_2)
        self.SQ1SLIDER_5 = QtGui.QSlider(self.widgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SQ1SLIDER_5.sizePolicy().hasHeightForWidth())
        self.SQ1SLIDER_5.setSizePolicy(sizePolicy)
        self.SQ1SLIDER_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.SQ1SLIDER_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SQ1SLIDER_5.setMinimum(0)
        self.SQ1SLIDER_5.setMaximum(9)
        self.SQ1SLIDER_5.setSingleStep(1)
        self.SQ1SLIDER_5.setPageStep(1)
        self.SQ1SLIDER_5.setProperty("value", 0)
        self.SQ1SLIDER_5.setOrientation(QtCore.Qt.Horizontal)
        self.SQ1SLIDER_5.setTickPosition(QtGui.QSlider.NoTicks)
        self.SQ1SLIDER_5.setTickInterval(0)
        self.SQ1SLIDER_5.setObjectName(_fromUtf8("SQ1SLIDER_5"))
        self.horizontalLayout_9.addWidget(self.SQ1SLIDER_5)
        self.tgLabel = QtGui.QLabel(self.widgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgLabel.sizePolicy().hasHeightForWidth())
        self.tgLabel.setSizePolicy(sizePolicy)
        self.tgLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.tgLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tgLabel.setObjectName(_fromUtf8("tgLabel"))
        self.horizontalLayout_9.addWidget(self.tgLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.trigBox = QtGui.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trigBox.setFont(font)
        self.trigBox.setObjectName(_fromUtf8("trigBox"))
        self.horizontalLayout_3.addWidget(self.trigBox)
        self.pushButton = QtGui.QPushButton(self.widgets)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_7 = QtGui.QFrame(self.widgets)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout.addWidget(self.line_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_6 = QtGui.QPushButton(self.widgets)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout.addWidget(self.pushButton_6)
        self.line = QtGui.QFrame(self.widgets)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.experimentBox = QtGui.QComboBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.experimentBox.setFont(font)
        self.experimentBox.setMaxCount(200)
        self.experimentBox.setFrame(False)
        self.experimentBox.setObjectName(_fromUtf8("experimentBox"))
        self.horizontalLayout.addWidget(self.experimentBox)
        self.pushButton_2 = QtGui.QPushButton(self.widgets)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.widgets)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.pauseBox = QtGui.QCheckBox(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pauseBox.setFont(font)
        self.pauseBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pauseBox.setObjectName(_fromUtf8("pauseBox"))
        self.verticalLayout.addWidget(self.pauseBox)
        self.horizontalLayout_2.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/control/plots.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, _fromUtf8(""))
        self.controlTab = QtGui.QWidget()
        self.controlTab.setObjectName(_fromUtf8("controlTab"))
        self.frame_12 = QtGui.QFrame(self.controlTab)
        self.frame_12.setGeometry(QtCore.QRect(10, 60, 300, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_12.setStyleSheet(_fromUtf8(""))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_7 = QtGui.QFrame(self.frame_12)
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setHorizontalSpacing(3)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.timeoutBox = QtGui.QSpinBox(self.frame_7)
        self.timeoutBox.setMinimum(10)
        self.timeoutBox.setMaximum(10000)
        self.timeoutBox.setObjectName(_fromUtf8("timeoutBox"))
        self.gridLayout_4.addWidget(self.timeoutBox, 4, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_4.addWidget(self.pushButton_7, 4, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_7)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 4, 0, 1, 2)
        self.edge2edge = QtGui.QComboBox(self.frame_7)
        self.edge2edge.setObjectName(_fromUtf8("edge2edge"))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.edge2edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2edge, 3, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 4)
        self.label_16 = QtGui.QLabel(self.frame_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 1)
        self.edge1edge = QtGui.QComboBox(self.frame_7)
        self.edge1edge.setObjectName(_fromUtf8("edge1edge"))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.edge1edge.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1edge, 2, 2, 1, 1)
        self.edge2chan = QtGui.QComboBox(self.frame_7)
        self.edge2chan.setObjectName(_fromUtf8("edge2chan"))
        self.gridLayout_4.addWidget(self.edge2chan, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.edge1chan = QtGui.QComboBox(self.frame_7)
        self.edge1chan.setObjectName(_fromUtf8("edge1chan"))
        self.gridLayout_4.addWidget(self.edge1chan, 2, 1, 1, 1)
        self.edge1Count = QtGui.QComboBox(self.frame_7)
        self.edge1Count.setObjectName(_fromUtf8("edge1Count"))
        self.edge1Count.addItem(_fromUtf8(""))
        self.edge1Count.addItem(_fromUtf8(""))
        self.edge1Count.addItem(_fromUtf8(""))
        self.edge1Count.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge1Count, 2, 3, 1, 1)
        self.edge2Count = QtGui.QComboBox(self.frame_7)
        self.edge2Count.setObjectName(_fromUtf8("edge2Count"))
        self.edge2Count.addItem(_fromUtf8(""))
        self.edge2Count.addItem(_fromUtf8(""))
        self.edge2Count.addItem(_fromUtf8(""))
        self.edge2Count.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.edge2Count, 3, 3, 1, 1)
        self.timingResults = QtGui.QTableWidget(self.frame_7)
        self.timingResults.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timingResults.setShowGrid(True)
        self.timingResults.setCornerButtonEnabled(True)
        self.timingResults.setRowCount(4)
        self.timingResults.setColumnCount(2)
        self.timingResults.setObjectName(_fromUtf8("timingResults"))
        self.timingResults.horizontalHeader().setVisible(False)
        self.timingResults.horizontalHeader().setDefaultSectionSize(115)
        self.timingResults.horizontalHeader().setMinimumSectionSize(60)
        self.timingResults.horizontalHeader().setStretchLastSection(True)
        self.timingResults.verticalHeader().setDefaultSectionSize(22)
        self.timingResults.verticalHeader().setMinimumSectionSize(20)
        self.timingResults.verticalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.timingResults, 10, 0, 1, 4)
        self.gridLayout_2.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_13 = QtGui.QFrame(self.controlTab)
        self.frame_13.setGeometry(QtCore.QRect(320, 60, 300, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_13.setStyleSheet(_fromUtf8(""))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_13)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_8 = QtGui.QFrame(self.frame_13)
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setHorizontalSpacing(3)
        self.gridLayout_6.setVerticalSpacing(1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.TimeoutBox = QtGui.QSpinBox(self.frame_8)
        self.TimeoutBox.setMinimum(10)
        self.TimeoutBox.setMaximum(10000)
        self.TimeoutBox.setObjectName(_fromUtf8("TimeoutBox"))
        self.gridLayout_6.addWidget(self.TimeoutBox, 4, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_6.addWidget(self.pushButton_8, 4, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_8)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 4, 0, 1, 2)
        self.Edge2edge = QtGui.QComboBox(self.frame_8)
        self.Edge2edge.setObjectName(_fromUtf8("Edge2edge"))
        self.Edge2edge.addItem(_fromUtf8(""))
        self.Edge2edge.addItem(_fromUtf8(""))
        self.Edge2edge.addItem(_fromUtf8(""))
        self.Edge2edge.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Edge2edge, 3, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_6.addWidget(self.label_57, 0, 0, 1, 4)
        self.label_18 = QtGui.QLabel(self.frame_8)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)
        self.Edge1edge = QtGui.QComboBox(self.frame_8)
        self.Edge1edge.setObjectName(_fromUtf8("Edge1edge"))
        self.Edge1edge.addItem(_fromUtf8(""))
        self.Edge1edge.addItem(_fromUtf8(""))
        self.Edge1edge.addItem(_fromUtf8(""))
        self.Edge1edge.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Edge1edge, 2, 2, 1, 1)
        self.Edge2chan = QtGui.QComboBox(self.frame_8)
        self.Edge2chan.setObjectName(_fromUtf8("Edge2chan"))
        self.gridLayout_6.addWidget(self.Edge2chan, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame_8)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 3, 0, 1, 1)
        self.Edge1chan = QtGui.QComboBox(self.frame_8)
        self.Edge1chan.setObjectName(_fromUtf8("Edge1chan"))
        self.gridLayout_6.addWidget(self.Edge1chan, 2, 1, 1, 1)
        self.Edge1Count = QtGui.QComboBox(self.frame_8)
        self.Edge1Count.setObjectName(_fromUtf8("Edge1Count"))
        self.Edge1Count.addItem(_fromUtf8(""))
        self.Edge1Count.addItem(_fromUtf8(""))
        self.Edge1Count.addItem(_fromUtf8(""))
        self.Edge1Count.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Edge1Count, 2, 3, 1, 1)
        self.Edge2Count = QtGui.QComboBox(self.frame_8)
        self.Edge2Count.setObjectName(_fromUtf8("Edge2Count"))
        self.Edge2Count.addItem(_fromUtf8(""))
        self.Edge2Count.addItem(_fromUtf8(""))
        self.Edge2Count.addItem(_fromUtf8(""))
        self.Edge2Count.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Edge2Count, 3, 3, 1, 1)
        self.TimingResults = QtGui.QTableWidget(self.frame_8)
        self.TimingResults.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TimingResults.setShowGrid(True)
        self.TimingResults.setCornerButtonEnabled(True)
        self.TimingResults.setRowCount(4)
        self.TimingResults.setColumnCount(2)
        self.TimingResults.setObjectName(_fromUtf8("TimingResults"))
        self.TimingResults.horizontalHeader().setVisible(False)
        self.TimingResults.horizontalHeader().setDefaultSectionSize(115)
        self.TimingResults.horizontalHeader().setMinimumSectionSize(60)
        self.TimingResults.horizontalHeader().setStretchLastSection(True)
        self.TimingResults.verticalHeader().setDefaultSectionSize(22)
        self.TimingResults.verticalHeader().setMinimumSectionSize(20)
        self.TimingResults.verticalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.TimingResults, 10, 0, 1, 4)
        self.gridLayout_5.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_14 = QtGui.QFrame(self.controlTab)
        self.frame_14.setGeometry(QtCore.QRect(10, 295, 300, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_14.setStyleSheet(_fromUtf8(""))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_14)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_9 = QtGui.QFrame(self.frame_14)
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setHorizontalSpacing(3)
        self.gridLayout_8.setVerticalSpacing(1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.timeoutBox_3 = QtGui.QSpinBox(self.frame_9)
        self.timeoutBox_3.setMinimum(10)
        self.timeoutBox_3.setMaximum(10000)
        self.timeoutBox_3.setObjectName(_fromUtf8("timeoutBox_3"))
        self.gridLayout_8.addWidget(self.timeoutBox_3, 3, 2, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_8.addWidget(self.pushButton_9, 3, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_9)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 3, 0, 1, 2)
        self.label_58 = QtGui.QLabel(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_8.addWidget(self.label_58, 0, 0, 1, 4)
        self.label_20 = QtGui.QLabel(self.frame_9)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 2, 0, 1, 1)
        self.edge1edge_3 = QtGui.QComboBox(self.frame_9)
        self.edge1edge_3.setObjectName(_fromUtf8("edge1edge_3"))
        self.edge1edge_3.addItem(_fromUtf8(""))
        self.edge1edge_3.addItem(_fromUtf8(""))
        self.edge1edge_3.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.edge1edge_3, 2, 2, 1, 1)
        self.edge1chan_3 = QtGui.QComboBox(self.frame_9)
        self.edge1chan_3.setObjectName(_fromUtf8("edge1chan_3"))
        self.gridLayout_8.addWidget(self.edge1chan_3, 2, 1, 1, 1)
        self.edge1Count_3 = QtGui.QComboBox(self.frame_9)
        self.edge1Count_3.setObjectName(_fromUtf8("edge1Count_3"))
        self.edge1Count_3.addItem(_fromUtf8(""))
        self.edge1Count_3.addItem(_fromUtf8(""))
        self.edge1Count_3.addItem(_fromUtf8(""))
        self.edge1Count_3.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.edge1Count_3, 2, 3, 1, 1)
        self.timingResults_3 = QtGui.QTableWidget(self.frame_9)
        self.timingResults_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.timingResults_3.setShowGrid(True)
        self.timingResults_3.setCornerButtonEnabled(True)
        self.timingResults_3.setRowCount(4)
        self.timingResults_3.setColumnCount(1)
        self.timingResults_3.setObjectName(_fromUtf8("timingResults_3"))
        self.timingResults_3.horizontalHeader().setVisible(False)
        self.timingResults_3.horizontalHeader().setDefaultSectionSize(115)
        self.timingResults_3.horizontalHeader().setMinimumSectionSize(60)
        self.timingResults_3.horizontalHeader().setStretchLastSection(True)
        self.timingResults_3.verticalHeader().setDefaultSectionSize(22)
        self.timingResults_3.verticalHeader().setMinimumSectionSize(20)
        self.timingResults_3.verticalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.timingResults_3, 9, 0, 1, 4)
        self.gridLayout_7.addWidget(self.frame_9, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.controlTab)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.DIN_IN2 = QtGui.QLabel(self.groupBox)
        self.DIN_IN2.setStyleSheet(_fromUtf8(""))
        self.DIN_IN2.setObjectName(_fromUtf8("DIN_IN2"))
        self.horizontalLayout_11.addWidget(self.DIN_IN2)
        self.DIN_SQR1 = QtGui.QLabel(self.groupBox)
        self.DIN_SQR1.setObjectName(_fromUtf8("DIN_SQR1"))
        self.horizontalLayout_11.addWidget(self.DIN_SQR1)
        self.DIN_OD1 = QtGui.QLabel(self.groupBox)
        self.DIN_OD1.setObjectName(_fromUtf8("DIN_OD1"))
        self.horizontalLayout_11.addWidget(self.DIN_OD1)
        self.DIN_SEN = QtGui.QLabel(self.groupBox)
        self.DIN_SEN.setObjectName(_fromUtf8("DIN_SEN"))
        self.horizontalLayout_11.addWidget(self.DIN_SEN)
        self.DIN_CCS = QtGui.QLabel(self.groupBox)
        self.DIN_CCS.setObjectName(_fromUtf8("DIN_CCS"))
        self.horizontalLayout_11.addWidget(self.DIN_CCS)
        self.tabWidget.addTab(self.controlTab, _fromUtf8(""))
        self.experimentTab = QtGui.QWidget()
        self.experimentTab.setObjectName(_fromUtf8("experimentTab"))
        self.experimentLayout = QtGui.QVBoxLayout(self.experimentTab)
        self.experimentLayout.setMargin(0)
        self.experimentLayout.setObjectName(_fromUtf8("experimentLayout"))
        self.tabWidget.addTab(self.experimentTab, _fromUtf8(""))
        self.saveTab = QtGui.QWidget()
        self.saveTab.setObjectName(_fromUtf8("saveTab"))
        self.saveLayout = QtGui.QVBoxLayout(self.saveTab)
        self.saveLayout.setMargin(0)
        self.saveLayout.setSpacing(0)
        self.saveLayout.setObjectName(_fromUtf8("saveLayout"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/control/saved.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.saveTab, icon1, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.A1RANGEBOX.setCurrentIndex(2)
        self.A1RANGEBOX_2.setCurrentIndex(2)
        self.chan1Box.setCurrentIndex(-1)
        self.edge2edge.setCurrentIndex(1)
        self.edge1Count.setCurrentIndex(0)
        self.Edge2edge.setCurrentIndex(1)
        self.Edge1Count.setCurrentIndex(0)
        self.edge1Count_3.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.save)
        QtCore.QObject.connect(self.A1RANGEBOX, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainA1)
        QtCore.QObject.connect(self.A1RANGEBOX_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainA2)
        QtCore.QObject.connect(self.comboBox_4, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainA3)
        QtCore.QObject.connect(self.comboBox_5, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setGainMIC)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.setSineAmp)
        QtCore.QObject.connect(self.chan1Box, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.setCH1Remap)
        QtCore.QObject.connect(self.SQ1SLIDER_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.setTimebase)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.measure_interval)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.DoubleInputInterval)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.tabChanged)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.launchExperiment)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ExpEYES - 17", None))
        self.widgets.setProperty("class", _translate("MainWindow", "deep", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "SINE .1V", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "SINE 1V", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "SINE 3V", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "TRIA .1V", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "TRIA 1V", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "TRIA 3V", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "SQR2", None))
        self.label_3.setText(_translate("MainWindow", "WG", None))
        self.checkBox_2.setText(_translate("MainWindow", "OD1", None))
        self.checkBox_3.setText(_translate("MainWindow", "CCS", None))
        self.label.setText(_translate("MainWindow", "Set Outputs", None))
        self.label_8.setText(_translate("MainWindow", "Four Channel Oscilloscope", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "4V", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2V", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "1V", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", ".5V", None))
        self.A3.setText(_translate("MainWindow", "A3", None))
        self.A1RANGEBOX.setItemText(0, _translate("MainWindow", "16V", None))
        self.A1RANGEBOX.setItemText(1, _translate("MainWindow", "8V", None))
        self.A1RANGEBOX.setItemText(2, _translate("MainWindow", "4V", None))
        self.A1RANGEBOX.setItemText(3, _translate("MainWindow", "2.5V", None))
        self.A1RANGEBOX.setItemText(4, _translate("MainWindow", "1.5V", None))
        self.A1RANGEBOX.setItemText(5, _translate("MainWindow", "1V", None))
        self.A1RANGEBOX.setItemText(6, _translate("MainWindow", ".5V", None))
        self.A1RANGEBOX.setItemText(7, _translate("MainWindow", ".25V", None))
        self.A2.setText(_translate("MainWindow", "A2", None))
        self.A1RANGEBOX_2.setItemText(0, _translate("MainWindow", "16V", None))
        self.A1RANGEBOX_2.setItemText(1, _translate("MainWindow", "8V", None))
        self.A1RANGEBOX_2.setItemText(2, _translate("MainWindow", "4V", None))
        self.A1RANGEBOX_2.setItemText(3, _translate("MainWindow", "2.5V", None))
        self.A1RANGEBOX_2.setItemText(4, _translate("MainWindow", "1.5V", None))
        self.A1RANGEBOX_2.setItemText(5, _translate("MainWindow", "1V", None))
        self.A1RANGEBOX_2.setItemText(6, _translate("MainWindow", ".5V", None))
        self.A1RANGEBOX_2.setItemText(7, _translate("MainWindow", ".25V", None))
        self.MIC.setText(_translate("MainWindow", "MIC", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "4V", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2V", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "1V", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", ".5V", None))
        self.label_4.setText(_translate("MainWindow", "FIT", None))
        self.label_6.setText(_translate("MainWindow", "Range", None))
        self.label_7.setText(_translate("MainWindow", "Input", None))
        self.tgLabel_2.setText(_translate("MainWindow", "Time", None))
        self.tgLabel.setText(_translate("MainWindow", "mS", None))
        self.trigBox.setText(_translate("MainWindow", "Trigger: 0V (Drag yellow line)", None))
        self.pushButton.setText(_translate("MainWindow", "?", None))
        self.pushButton.setShortcut(_translate("MainWindow", "T", None))
        self.pushButton_6.setText(_translate("MainWindow", "Save Data", None))
        self.pushButton_6.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.pushButton_2.setText(_translate("MainWindow", "LAUNCH", None))
        self.pauseBox.setText(_translate("MainWindow", "PAUSE", None))
        self.pauseBox.setShortcut(_translate("MainWindow", "Space", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Oscilloscope", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data Acquisition and controls", None))
        self.frame_12.setProperty("class", _translate("MainWindow", "deep", None))
        self.frame_7.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.timeoutBox.setSuffix(_translate("MainWindow", "mS", None))
        self.pushButton_7.setText(_translate("MainWindow", "Measure >", None))
        self.label_2.setText(_translate("MainWindow", "Timeout:", None))
        self.edge2edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge2edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge2edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_56.setText(_translate("MainWindow", "TIME INTERVAL MEASUREMENT", None))
        self.label_16.setText(_translate("MainWindow", "1", None))
        self.edge1edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge1edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge1edge.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.label_17.setText(_translate("MainWindow", "2", None))
        self.edge1Count.setItemText(0, _translate("MainWindow", "1", None))
        self.edge1Count.setItemText(1, _translate("MainWindow", "2", None))
        self.edge1Count.setItemText(2, _translate("MainWindow", "3", None))
        self.edge1Count.setItemText(3, _translate("MainWindow", "4", None))
        self.edge2Count.setItemText(0, _translate("MainWindow", "1", None))
        self.edge2Count.setItemText(1, _translate("MainWindow", "2", None))
        self.edge2Count.setItemText(2, _translate("MainWindow", "3", None))
        self.edge2Count.setItemText(3, _translate("MainWindow", "4", None))
        self.frame_13.setProperty("class", _translate("MainWindow", "deep", None))
        self.frame_8.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.TimeoutBox.setSuffix(_translate("MainWindow", "mS", None))
        self.pushButton_8.setText(_translate("MainWindow", "Measure >", None))
        self.label_5.setText(_translate("MainWindow", "Timeout:", None))
        self.Edge2edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.Edge2edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.Edge2edge.setItemText(2, _translate("MainWindow", "4xrising", None))
        self.Edge2edge.setItemText(3, _translate("MainWindow", "16xrising", None))
        self.label_57.setText(_translate("MainWindow", "DOUBLE INPUT INTERVAL", None))
        self.label_18.setText(_translate("MainWindow", "1", None))
        self.Edge1edge.setItemText(0, _translate("MainWindow", "rising", None))
        self.Edge1edge.setItemText(1, _translate("MainWindow", "falling", None))
        self.Edge1edge.setItemText(2, _translate("MainWindow", "4xrising", None))
        self.Edge1edge.setItemText(3, _translate("MainWindow", "16xrising", None))
        self.label_19.setText(_translate("MainWindow", "2", None))
        self.Edge1Count.setItemText(0, _translate("MainWindow", "1", None))
        self.Edge1Count.setItemText(1, _translate("MainWindow", "2", None))
        self.Edge1Count.setItemText(2, _translate("MainWindow", "3", None))
        self.Edge1Count.setItemText(3, _translate("MainWindow", "4", None))
        self.Edge2Count.setItemText(0, _translate("MainWindow", "1", None))
        self.Edge2Count.setItemText(1, _translate("MainWindow", "2", None))
        self.Edge2Count.setItemText(2, _translate("MainWindow", "3", None))
        self.Edge2Count.setItemText(3, _translate("MainWindow", "4", None))
        self.frame_14.setProperty("class", _translate("MainWindow", "deep", None))
        self.frame_9.setProperty("class", _translate("MainWindow", "PeripheralCollectionInner", None))
        self.timeoutBox_3.setSuffix(_translate("MainWindow", "mS", None))
        self.pushButton_9.setText(_translate("MainWindow", "Measure >", None))
        self.label_9.setText(_translate("MainWindow", "Timeout:", None))
        self.label_58.setText(_translate("MainWindow", "SINGLE INPUT INTERVAL", None))
        self.label_20.setText(_translate("MainWindow", "1", None))
        self.edge1edge_3.setItemText(0, _translate("MainWindow", "rising", None))
        self.edge1edge_3.setItemText(1, _translate("MainWindow", "falling", None))
        self.edge1edge_3.setItemText(2, _translate("MainWindow", "four rising edges", None))
        self.edge1Count_3.setItemText(0, _translate("MainWindow", "1", None))
        self.edge1Count_3.setItemText(1, _translate("MainWindow", "2", None))
        self.edge1Count_3.setItemText(2, _translate("MainWindow", "3", None))
        self.edge1Count_3.setItemText(3, _translate("MainWindow", "4", None))
        self.groupBox.setTitle(_translate("MainWindow", "Digital Inputs", None))
        self.DIN_IN2.setText(_translate("MainWindow", "IN2", None))
        self.DIN_SQR1.setText(_translate("MainWindow", "SQR1", None))
        self.DIN_OD1.setText(_translate("MainWindow", "OD1", None))
        self.DIN_SEN.setText(_translate("MainWindow", "SEN", None))
        self.DIN_CCS.setText(_translate("MainWindow", "CCS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlTab), _translate("MainWindow", "Measurement and Controls", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.experimentTab), _translate("MainWindow", "Experiments", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saveTab), _translate("MainWindow", "Saved plots", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.saveTab), _translate("MainWindow", "View saved plots. Click on them to load them to the plot window for analysis", None))

import res_rc
